language: c
sudo:     required

services:
    - docker

compiler:
  - clang

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
install:
  - sudo apt-get update
  - sudo apt-get install emscripten
  - sudo apt-get intsall python
  - sudo apt-get install xutils-dev
script:
  - mkdir build
  - cd build && emcmake cmake .. && emmake make
