language: c
sudo:     required

services:
    - docker

compiler:
  - clang

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
install:
  - sudo apt-get update
  - sudo apt-get install cmake xutils-dev -qq
  - sudo apt-get install python2.7 nodejs default-jre -qq
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar zxvf emsdk-portable.tar.gz
  - cd emsdk_portable && ./emsdk update && ./emsdk install latest && ./emsdk activate latest && ls
script:
  - mkdir build
  - cd build && emcmake cmake .. && emmake make
